<?php echo $this->form()->openTag($this->form); ?>
<table class="table" id="assetRequirements">
    <tr>
        <th>class</th>
        <th><?php echo $this->FormText($this->form->get('class')); ?></th>
    </tr>
    <tr>
        <th>Code</th>
        <th><?php echo $this->FormTextArea($this->form->get('code')); ?></th>
    </tr>
</table>
<button type="submit" class="btn btn-primary">Go</button>
<?php
echo $this->form()->closeTag($this->form);
?>

<pre>
    
<?php echo $this->result ?>
</pre>