<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Jasmine Spec Runner</title>

        <link rel="shortcut icon" type="image/png" href="/js/jasmine/lib/jasmine_favicon.png">
        <link rel="stylesheet" type="text/css" href="/js/jasmine/lib/jasmine.css">

        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.10.2.custom.min.js"></script>

        <script type="text/javascript" src="/js/jasmine/lib/jasmine.js"></script>
        <script type="text/javascript" src="/js/jasmine/lib/jasmine-html.js"></script>
        <?php foreach ($this->requiredFiles as $file) : ?>
            <script type="text/javascript" src="<?php echo $file ?>"></script>
        <?php endforeach; ?>     

        <script type="text/javascript" src="/js/jasmine/src/specs/<?php echo $specFile ?>"></script>     





        <script type="text/javascript">
            (function() {
                var jasmineEnv = jasmine.getEnv();
                jasmineEnv.updateInterval = 1000;
                var htmlReporter = new jasmine.HtmlReporter();

                jasmineEnv.addReporter(htmlReporter);
                jasmineEnv.specFilter = function(spec) {
                    return htmlReporter.specFilter(spec);
                };

                var currentWindowOnload = window.onload;

                window.onload = function() {
                    if (currentWindowOnload) {
                        currentWindowOnload();
                    }
                    execJasmine();
                };

                function execJasmine() {
                    jasmineEnv.execute();

                }

            })();
        </script>

    </head>

    <body>

    </body>
</html>
