<?php

var_dump($this->allGetParameters);
unset($this->allGetParameters['filter']);
$thisBaseUrl = "?" . http_build_query($this->allGetParameters['filter']);
$filter = $this->filter;
?>
<h1><?php echo $this->test ?></h1>
<?php if ($filter) : ?>
    <h2><?php echo $this->filter ?></h2>
<?php endif; ?>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Filter<span class="caret"></span>
  </button>
<ul class="dropdown-menu" role="menu">
    <li><a href="<?php echo $thisBaseUrl?>">ALL</a></li>
    <?php foreach ($this->filters as $method): ?>
               <li><a href="<?php echo $thisBaseUrl?>&filter=<?php echo $method?>"><?php echo $method?></a></li>
    <?php endforeach; ?>
    
</ul>
    </div>
 <?php foreach($this->testResults as $result): ?>
    <?php if ( $result['event'] != 'test'):
        continue;
    endif; ?>
    <?php if($result['status']=='error' || $result['status']=='fail'):?>
        <?php if(strpos($result['Skipped Test'], 'Skipped Test')===0):?>
        <div class="alert alert-warning">Skipped: <?php echo $result['test']; ?></div>
        <?php else: ?>
        <div class="alert alert-danger">Failed: <?php echo $result['test']; ?></div>
        <pre><?php echo $result['message']; ?></pre>
        <?php endif; ?>
        <?php else: ?>
        <div class="alert alert-success">Passed: <?php echo $result['test']; ?></div>
    <?php endif; ?>
 <?php endforeach; ?>

